apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: flink-job:1.10.1-example
        command: ["/bin/bash", "-c", "$FLINK_HOME/bin/taskmanager.sh start;
        sleep 3;
        tail -f $FLINK_HOME/log/*.log"]
        ports:
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query-state
        livenessProbe:
#          tcpSocket:
#            port: 6122
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "curl -s http://flink-jobmanager:8081/taskmanagers|grep `hostname -i`"
          initialDelaySeconds: 30
          periodSeconds: 60
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf/
        - name: flink-data
          mountPath: /data
        securityContext:
          runAsUser: 9999  # refers to user _flink_ from official flink image, change if necessary
      volumes:
      - name: flink-config-volume
        configMap:
          name: flink-config
          items:
          - key: flink-conf.yaml
            path: flink-conf.yaml
          - key: log4j.properties
            path: log4j.properties
          - key: log4j-console.properties
            path: log4j-console.properties
      - name: flink-data
        persistentVolumeClaim:
          claimName: flinknfspvc
